config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do 
    resources :posts
  end

end

app/models/article.rb
require 'elasticsearch/model'
# require 'elasticsearch'
# require 'elasticsearch/persistence'
class Article < ActiveRecord::Base
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  extend ActiveSupport::Concern
  has_many :posts

  # index_name    "articles-#{Rails.env}"
  # document_type "post"
  # index_name Rails.application.class.parent_name.underscore
  # document_type self.name.downcase

  

  # settings index: { number_of_shards: 1, number_of_replicas: 0 } do
  #   mapping dynamic: false do 

  #     indexes :id, type: 'long'
  #     indexes :title, type: 'string'
  #     indexes :description, type: 'string'
  #     # indexes :family_id, type: 'long'
  #     # indexes :collection_id, type: 'long'
  #     # indexes :created_at, type: 'date'
  #     # indexes :updated_at, type: 'date'

  #     indexes :posts, type: 'nested' do
  #       indexes :id, type: 'long'
  #       indexes :title, type: 'string'
  #     end

  #     # indexes :categories, type: 'nested' do
  #     #   indexes :id, type: 'long'
  #     #   indexes :name, type: 'string'
  #     # end

  #   end
  # end

  # def as_indexed_json
  #   self.as_json({
  #     only: [:title, :description],
  #     include: {
  #       posts: { only: :title },
  #     }
  #   })
  # end


  # settings index: { number_of_shards: 1 } do
  #   mappings dynamic: 'false' do
  #     indexes :title, analyzer: 'english', index_options: 'offsets'
  #   end
  # end

  def as_indexed_json(options={})
    as_json({
      only: ['title','created_at', 'description'],
      methods: [],
      include: {
        posts: {only: [:title, :description] }
      }   
    })  
  end 

   mapping _source: { excludes: [] } do
    indexes :id, type: 'integer'
    indexes :title
  end

  # Article.search('*foo*').results.as_json
  def self.search(query, post_q = '')
    fields_data = nil
    if query.present?
      fields_data = ["title"]
      query_input = query
    elsif post_q.present?
      fields_data = ["posts.title"]
      query_input = post_q
    else
      fields_data = ["title"]
      query_input = query
    end

    __elasticsearch__.search(
      # {
      #   query: {
      #     multi_match: {
      #       query: query,
      #       fields: ['title', 'description', "posts.title"]
      #     }
      #   },
      #   highlight: {
      #     pre_tags: ['<em>'],
      #     post_tags: ['</em>'],
      #     fields: {
      #       title: {},
      #       text: {}
      #     }
      #   }
      # }
      {:query=>{
        :filtered=>{
          :query=>{
            :query_string=>{
              :query=> query_input, 
              :fields=>fields_data
            }
          }, 
          :filter=>{
            :bool=>{
              :should=>[
                { 
                  :terms=>{"posts.title"=> [post_q] } 
                },
                :range=>{
                  :created_at=>{
                    :gt=>"now-1w"
                  }
                }
              ] 
              # :should=>[]
            }
            }
          }
        }
      }
    )
  
end


#  def self.search(query)
#   __elasticsearch__.search(
#     {
#       query: {
#         multi_match: {
#           query: query,
#           fields: ['title']
#         }
#       },
#       highlight: {
#         pre_tags: ['<em>'],
#         post_tags: ['</em>'],
#         fields: {
#           title: {},
#           text: {}
#         }
#       }
#     }
#   )
# end

    # settings index: { number_of_shards: 1, number_of_replicas: 0 } do
    #   mapping do

    #     indexes :id, type: 'long'
    #     indexes :title, type: 'string'
    #     indexes :description, type: 'string'
    #     # indexes :family_id, type: 'long'
    #     # indexes :collection_id, type: 'long'
    #     # indexes :created_at, type: 'date'
    #     # indexes :updated_at, type: 'date'

    #     indexes :posts, type: 'nested' do
    #       indexes :id, type: 'long'
    #       indexes :title, type: 'string'
    #     end

    #     # indexes :categories, type: 'nested' do
    #     #   indexes :id, type: 'long'
    #     #   indexes :name, type: 'string'
    #     # end

    #   end
    # end

  #   def self.search(options={})
  #     __set_filters = lambda do |key, f|

  #       @search_definition[:filter][:and] ||= []
  #       @search_definition[:filter][:and]  |= [f]
  #     end

  #     @search_definition = {
  #       query: {
  #         filtered: {
  #           query: {
  #             match_all: {}
  #           }
  #         }
  #       },
  #       filter: {}
  #     }

  #     if options[:article]
  #       f = { term: { "title": options[:article] } }

  #       __set_filters.(:title, f)
  #       __set_filters.(:description, f)
  #       # __set_filters.(:categories, f)
  #     end

  #     def as_indexed_json(options={})
  #       as_json(
  #         include: {:posts => { :only => [ :id, :title ] }
  #       )
  #     end

  #     # if options[:categories]
  #     #   ...
  #     # end

  #     # if options[:collection_id]
  #     #   ...
  #     # end

  #     # if options[:family_id]
  #     #   ...
  #     # end

  #     __elasticsearch__.search(@search_definition)
  #   end

  # end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:q].present? or params[:q1]
      @articles =  Article.search((params[:q].present? ? '*'+params[:q]+'*' : ''), params[:q1]).records.to_a
    else
      @articles = Article.all 

    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h5>Editing Article</h5>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h5>Listing Articles</h5>
<%= form_tag articles_path, method: :get do %>
  <%= text_field_tag :q, params[:q]  %>
  <%= text_field_tag :q1, params[:q1]  %>
  <%= submit_tag %>
<% end %>

<% if true #not params[:q].present? %>
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.description %></td>
          <td><%= link_to 'Posts',[article, Post] %></td>
          <td><%= link_to 'Show', article %></td>
          <td><%= link_to 'Edit', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'New Article', new_article_path %>

<% else %>

<% end %>

app/views/articles/new.html.erb
<h5>New Article</h5>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>